[project]
name = "ai-trip-planner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.120.1",
    "langchain-openai>=1.0.1",
    "streamlit>=1.50.0",
    "uvicorn>=0.38.0",
]
